local UI = Ambi.Packages.Out( 'ui' )

-- --------------------------------------------------------------------------------------------------------------------------------------------
local CATEGORY = 'Ambi'

UI.AddFontType( 'Ambi', 'Franklin Gothic Demi', CATEGORY, true, 100 )
UI.AddFontType( 'Ambi Bold', 'Franklin Gothic Demi', CATEGORY, true, 600 )
UI.AddFontType( 'Arial', 'Arial', CATEGORY, false, 100 )
UI.AddFontType( 'Arial Bold', 'Arial', CATEGORY, false, 600 )
UI.AddFontType( 'Arimo', 'Arimo', CATEGORY, true, 500 )
UI.AddFontType( 'Bebas Neue Book', 'Bebas Neue Book', CATEGORY, true, 100 )
UI.AddFontType( 'Bebas Neue Cyrillic', 'Bebas Neue Book', CATEGORY, true, 600 )
UI.AddFontType( 'Bookerly', 'Bookerly', CATEGORY, true )
UI.AddFontType( 'Bookerly Bold', 'Bookerly Bold', CATEGORY, true )
UI.AddFontType( 'Bookerly Italic', 'Bookerly Italic', CATEGORY, true )
UI.AddFontType( 'Bookerly Light', 'Bookerly Light', CATEGORY, true, 100 )
UI.AddFontType( 'BSB Text Classic', 'BSB Text Classic', CATEGORY, true )
UI.AddFontType( 'Caviar Dreams', 'Caviar Dreams', CATEGORY, true )
UI.AddFontType( 'Dewberry', 'Dewberry', CATEGORY, true )
UI.AddFontType( 'Eirik Raude', 'Eirik Raude', CATEGORY, true )
UI.AddFontType( 'Franklin Gothic Demi', 'Franklin Gothic Demi', CATEGORY, true )
UI.AddFontType( 'Franxurter Totally Fat', 'Franxurter Totally Fat', CATEGORY, true, 500 )
UI.AddFontType( 'Facile Sans', 'Facile Sans [RUS by Daymarius]', CATEGORY, true )
UI.AddFontType( 'Muller Thin Demo', 'Muller Thin DEMO', CATEGORY, true )
UI.AddFontType( 'Namu Pro', 'NAMU Pro', CATEGORY, true )
UI.AddFontType( 'Namu 1990', 'NAMU 1990', CATEGORY, true, 600 )
UI.AddFontType( 'Neuron', 'Neuron', CATEGORY, true )
UI.AddFontType( 'Nexa Script Light', 'Nexa Script Light', CATEGORY, true, 500 )
UI.AddFontType( 'Open Sans Condensed Light', 'Open Sans Condensed Light', CATEGORY, true, 500 )
UI.AddFontType( 'Oswald Light', 'Oswald Light', CATEGORY, true, 100 )
UI.AddFontType( 'Oswald ExtraLight', 'Oswald ExtraLight', CATEGORY, true, 100 )
UI.AddFontType( 'Patsy Sans', 'Patsy Sans', CATEGORY, true )
UI.AddFontType( 'Roboto Light', 'Roboto Light', CATEGORY, true )
UI.AddFontType( 'Roboto Medium', 'Roboto Medium', CATEGORY, true )
UI.AddFontType( 'Roboto Thin', 'Roboto Thin', CATEGORY, true )
UI.AddFontType( 'Slimamif Medium', 'SlimamifMedium', CATEGORY, true, 500 )
UI.AddFontType( 'Tantular', 'Tantular', CATEGORY, true )
UI.AddFontType( 'Tahoma', 'Tahoma', CATEGORY, true )
UI.AddFontType( 'Ubuntu', 'Ubuntu', CATEGORY, true )
UI.AddFontType( 'Ubuntu Italic', 'Ubuntu Italic', CATEGORY, true )
UI.AddFontType( 'Ubuntu Light', 'Ubuntu Light', CATEGORY, true, 100 )
UI.AddFontType( 'UZ Sans', 'UZ Sans Regular', CATEGORY, true )
UI.AddFontType( 'UZ Sans Bold', 'UZ Sans Bold', CATEGORY, true, 600 )
UI.AddFontType( 'UZ Sans Light', 'UZ Sans Lt', CATEGORY, true, 100 )
UI.AddFontType( 'Vinnytsia Sans', 'Vinnytsia Sans Regular', CATEGORY, true )
UI.AddFontType( 'Vinnytsia Sans Bold', 'Vinnytsia Sans Bold', CATEGORY, true, 600 )
UI.AddFontType( 'Vinnytsia Serif', 'Vinnytsia Serif Regular', CATEGORY, true )
UI.AddFontType( 'Yahfie', 'Yahfie', CATEGORY, true )

-- --------------------------------------------------------------------------------------------------------------------------------------------
local CATEGORY = 'Ambi Extended'

UI.AddFontType( 'Abaddon', 'Abaddon Cyr', CATEGORY, true )
UI.AddFontType( 'Alcotton', 'Alcotton', CATEGORY, true )
UI.AddFontType( 'Angry Birds', 'AngryBirds', CATEGORY, true )
UI.AddFontType( 'Appetite New', 'Appetite New', CATEGORY, true )
UI.AddFontType( 'Bernier Shade', 'BERNIER Shade', CATEGORY, true )
UI.AddFontType( 'Blood', 'Blood Cyrillic', CATEGORY, true )
UI.AddFontType( 'Brusher', 'Brusher', CATEGORY, true )
UI.AddFontType( 'BUD Pixel', 'BUD Pixel', CATEGORY, true )
UI.AddFontType( 'Caesar', 'Caesar Dressing Cyrillic', CATEGORY, true )
UI.AddFontType( 'Capture It', 'Capture It', CATEGORY, true )
UI.AddFontType( 'China', 'China', CATEGORY, true )
UI.AddFontType( 'Diablo', 'DiabloFont', CATEGORY, true )
UI.AddFontType( 'Dopegstyle', 'mr_DopestyleG', CATEGORY, true, 500 )
UI.AddFontType( 'Echo Revival', 'EchoRevival', CATEGORY, true )
UI.AddFontType( 'Foo', 'Foo', CATEGORY, true )
UI.AddFontType( 'Furore', 'Furore', CATEGORY, true )
UI.AddFontType( 'Getman', 'Getman', CATEGORY, true )
UI.AddFontType( 'Good Vibes Pro', 'Good Vibes Pro', CATEGORY, true )
UI.AddFontType( 'Kot Leopold', 'Kot Leopold', CATEGORY, true )
UI.AddFontType( 'Kunstler', '1 Kunstler Light', CATEGORY, true )
UI.AddFontType( 'Leo Hand', 'LeoHand', CATEGORY, true )
UI.AddFontType( 'Merkur', 'Merkur Cyrillic', CATEGORY, true )
UI.AddFontType( 'Namu 1400', 'NAMU 1400', CATEGORY, true )
UI.AddFontType( 'Namu 1600', 'NAMU 1600', CATEGORY, true )
UI.AddFontType( 'Nickainley', 'Nickainley Normal', CATEGORY, true )
UI.AddFontType( 'Obitaem Ostrov', 'ObitaemOstrov', CATEGORY, true )
UI.AddFontType( 'Old Horror Films', 'Old Horror Films', CATEGORY, true )
UI.AddFontType( 'Playskool 3D', 'PF Playskool Pro 3D', CATEGORY, true )
UI.AddFontType( 'Radiotechnika', 'Radiotechnika', CATEGORY, true )
UI.AddFontType( 'Sangha', 'Sangha', CATEGORY, true )
UI.AddFontType( 'Smeshariki', 'Smeshariki Font', CATEGORY, true )
UI.AddFontType( 'Spectral', 'Spectral', CATEGORY, true )
UI.AddFontType( 'Street Soul Cyrillic', 'Street Soul Cyrillic', CATEGORY, true )
UI.AddFontType( 'Thintel', 'Thintel', CATEGORY, true, 500 )
UI.AddFontType( 'Toyz', 'TOYZ', CATEGORY, true, 500 )
UI.AddFontType( 'Unutterable', 'Unutterable', CATEGORY, true )
UI.AddFontType( 'Vasek', 'Vasek', CATEGORY, true )
UI.AddFontType( 'Vetrino', 'Vetrino', CATEGORY, true )
UI.AddFontType( 'Zekton', 'Zekton Rg', CATEGORY, true )
UI.AddFontType( 'Slope Opera', 'Slope Opera', CATEGORY, true )
UI.AddFontType( 'Ge Body', 'Ge Body [RUS by Daymarius]', CATEGORY, true )